__default__:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=10g"

bowtie2_index:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

fastq_screen:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

markduplicates:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

merge_techreps:
  prefix: "--gres=lscratch:20 --time=4:00:00 --mem=32g"

bigwig_neg:
  prefix: "--gres=lscratch:20 --mem=16g"

bigwig_pos:
  prefix: "--gres=lscratch:20 --mem=16g"

macs2:
  prefix: "--gres=lscratch:20 --mem=16g"

fingerprint:
  prefix: "--gres=lscratch:20 --mem=32g"

spp:
  prefix: "--gres=lscratch:20 --time=6:00:00 --mem=16g"

fimo:
  prefix: "--gres=lscratch:20 --mem=45g"
